### ISSUE TITLE
PHP 7.1 issue

### ISSUE THREAD

**Issue by remicollet** [bukka/php-crypto#16]
Bulid is ok, but, trying to load the extension

    $ php --no-php-ini --define extension=modules/crypto.so --modules
    PHP Fatal error:  Cannot redefine class constant Crypto\MACException::ALGORITHM_NOT_FOUND in Unknown on line 0

**Comment by bukka** [comment]
Hi. It's already fixed in https://github.com/bukka/php-crypto/commit/ee493a2737fd29a8ff8c8e3dec7c6fa46822ef05 but it's not part of any release yet. I won't be probably able to release a new version before 7.1 is stable because this is API change and should go to next minor version where I also want more features and I'm quite busy with other stuff to write them now.

So the master needs to be used if you want to use the ext with PHP master. ;)

**Comment by remicollet** [comment]
Indeed the patch fix the issue, thanks.

**Comment by peternijssen** [comment]
Since PHP 7.1 is officially released, maybe we can tag a version?

**Comment by bukka** [comment]
Yeah I plan to do that once I finish docs for PBKDF2 and do a bit more testing. I'm working on the [next branch](https://github.com/bukka/php-crypto/tree/next) and once it's all done I will release 0.3.0. Shouldn't take too long hopefully.
